# Generated by Django 5.1.4 on 2025-01-09 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_rename_speacial_request_reservation_special_request'),
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reservation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation'),
        ),
    ]
