# Generated by Django 5.1.4 on 2024-12-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='address',
            new_name='full_address',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.ManyToManyField(related_name='restaurants', to='restaurants.city'),
        ),
    ]
