# Generated by Django 5.1.4 on 2025-01-09 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_blockeddate_restaurant_and_more'),
        ('restaurants', '0003_review_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation'),
        ),
    ]
