# Generated by Django 5.1.4 on 2024-12-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_restaurant_city_restaurant_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='max_dinning_time',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_number_of_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='min_number_of_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_start_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='summary',
            field=models.CharField(default='Default summary', max_length=255),
        ),
    ]
