# Generated by Django 5.1.4 on 2024-12-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_max_dinning_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cancellation_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='highlights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
