# Generated by Django 5.1.4 on 2024-12-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_cancellation_policy_restaurant_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
