# Generated by Django 5.1.4 on 2025-01-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_restaurant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='highlights',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='remarks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
