# Generated by Django 5.1.4 on 2025-01-02 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_rename_booking_reservation'),
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesshours',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='businesshours',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='blockeddate',
            name='restaurant',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='restaurant',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='restaurant',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='blockeddate',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='reservations.timeslot'),
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='break_between_slots',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='slot_duration',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='is_available',
        ),
    ]
